# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: heroku-trial_development
  pool: 5
#  username: root
#  password:
#  host: 127.0.0.1

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  username: root
  password: KIWIs836
  socket: /var/run/mysqld/mysqld.sock

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  #min_messages: warning

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
#  username: heroku-trial
  host: localhost
  port: 5000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: heroku-trial_production
  pool: 5
  username: bbcbadd2d1ae3a
  password: 1d01a547
  socket: /var/run/mysqld/mysqld.sock
